### ISSUE TITLE
Free Monad

### ISSUE THREAD

**Issue by ghost** [funcool/cats#115]
https://hackage.haskell.org/package/free-4.12.1/docs/Control-Monad-Free.html

**Comment by freckletonj** [comment]
I'm interested in a `cats` Free monad as well, that's why I'm switching to `cats` from `algo.monads` since `cats` seems more straight forward, and has significantly better docs, and I want to play around with the Free Monad (and Freer, and Free Applicative).

I'm excited to see what comes of this!
