### ISSUE TITLE
MonadZero for either?

### ISSUE THREAD

**Issue by muhuk** [funcool/cats#118]
Is there a reason either doesn't have a `MonadZero` implementation?

[Haskell's `Either` seems to have one](https://en.wikibooks.org/wiki/Haskell/MonadPlus).

If there are obstacles, I can perhaps pick this up. Just wanted to confirm it can be supported and you might be willing to merge a PR.

**Comment by dialelo** [comment]
Feel free to submit a patch, looks like we missed that one. Thanks in advance!

**Comment by yurrriq** [comment]
I've made a [first pass][]. It needs review and preferably tests.

PS I noticed there are no tests for `mzero` or `mplus`. We should probably remedy that.
```fish
$ ag mzero test; or echo "No mzero tests!"
No mzero tests!
$ ag mplus test; or echo "No mplus tests!"
No mplus tests!
```

[first pass]: https://github.com/funcool/cats/compare/master...monadzero-for-either

**Comment by muhuk** [comment]
Thanks @yurrriq.

I'm closing this since it's merged now.

**Comment by muhuk** [comment]
I don't suppose `1.1.0-SNAPSHOT` contains this. Could you possibly make a new snapshot/release?

**Comment by niwinz** [comment]
Done!

**Comment by muhuk** [comment]
Thanks, much appreciated.
