### ISSUE TITLE
Map implementation of Functor

### ISSUE THREAD

**Issue by tcsavage** [funcool/cats#131]
Map's implementation of Functor does not do what I'd expect:

    p/Functor
    (-fmap [_ f v]
      (into {} (map f v)))

It passes the map entries to f. Not just the values. The clojure.algo.generic implementation, and the Haskell implementation in Data.Map would look something like this:

    p/Functor
    (-fmap [_ f v]
      (into {} (map (fn [[key val]] [key (f val)]) v)))

I.e. the keys remain unchanged and f is applied to the values only. This is an example of how I would expect it to work:

    => (fmap inc {:a 1 :b 2})
    {:a 2 :b 3}

Why is it not implemented way?

**Comment by niwinz** [comment]
Hmm, maybe you are right! @dialelo @yurrriq That do you thing about?

**Comment by tcsavage** [comment]
:+1: I'll submit a PR then

**Comment by alesguzik** [comment]
Back when I were writing implementation of fmap for maps that behaviour was actually a design goal - to be able to pass a function to change not just values but keys as well. It treated a map as a sequence of key-value pairs (same way as `seq` treats it)
