### ISSUE TITLE
Error following the tutorial

### ISSUE THREAD

**Issue by rachbowyer** [funcool/cats#134]
I have a little bit of familiarity with monads from Scala, but was interested in trying them with Clojure. Have set [funcool/cats "1.2.0"] in my project.clj (although have the same problem with other versions). I tried the first two lines of the tutorial in my REPL:

    (require '[cats.core :as m])
    (m/mappend [1 2 3] [4 5 6])

And got the following back:

> IllegalArgumentException No context is set and it can not be automatically resolved.  sun.reflect.NativeConstructorAccessorImpl.newInstance0 (NativeConstructorAccessorImpl.java:-2)

At this point my worse nightmare of monadic abstractions is realised :-( I am only two lines into the tutorial and I already have an incomprehensible error message.

But seriously, not sure if I am making a mistake, there is a bug in the code, a step missing in the tutorial etc.

**Comment by rachbowyer** [comment]
Ok, have found the issue. I need to also require the following:

    (require '[cats.builtin])

Would it be possible to update the tutorial to include this. Also, is there any way the error messages could be made more friendly.

**Comment by niwinz** [comment]
This is an expected behavior. The clojure core  data types such as vectors, maps, etc.. are not extended by default. This is because the user may implement their own abstractions for that types. In summary, cats tries to be not very intrusive.

And you are right, the documentation is just missing that require in some examples. I'll keep this issue open until we fix it. Thanks!

**Comment by dialelo** [comment]
> At this point my worse nightmare of monadic abstractions is realised :-( I am only two lines into the tutorial and I already have an incomprehensible error message.

We should make the error message better too, thanks for reporting!

**Comment by dialelo** [comment]
The docs are now updated to reflect that `cats.builtin` has to be required. Please let us know if you encounter more problems!

**Comment by yurrriq** [comment]
:tada:
