### ISSUE TITLE
Sequence Monad for PersistentList

### ISSUE THREAD

**Issue by muhuk** [funcool/cats#142]
Is there a reason why there is no context for `PersistentList`?

If not, would you be interested in considering a PR implementing it? I'd like to give it a try.

**Comment by dialelo** [comment]
> Is there a reason why there is no context for PersistentList?

It seems we missed that one.

> If not, would you be interested in considering a PR implementing it? I'd like to give it a try.

Definitely, we extend the built-in types in the `cats.builtin` namespace. Looking forward to the PR, thanks for your time!

**Comment by yurrriq** [comment]
:+1:

**Comment by muhuk** [comment]
Can you please take a look at the PR?

**Comment by dialelo** [comment]
Sorry for the delay, will look at it ASAP. Thanks for your time!

**Comment by yurrriq** [comment]
Closing this since #143 is merged.
