### ISSUE TITLE
Should :scope be removed from lein :dependencies?

### ISSUE THREAD

**Issue by muhuk** [funcool/cats#144]
[Quoting from](http://librelist.com/browser//leiningen/2014/9/7/clarifications-about-scope-in-dependencies/#32fcd639eb09c94545bec6a56c200167):

> Leiningen uses profiles for this instead ... these days you should never have
to set it.

Should we remove `:scope`?

Also, if I'm reading this correctly, every project that uses cats pulls ClojureScript, core.async, test.check & manifold even if related modules are not used at all. May I suggest we require modules conditionally and throw meaningful exceptions when a project tries to use them without requiring the relevant lib. And moving those four into dev profile of course.

**Comment by niwinz** [comment]
I'm not agree that profiles substitutes the scope. And cats uses the scope properly.

And responding your second question; NO, the `:scope "provided"` is a non transitive dependency. If you are using cats, the rest of dependencies are not transitive to your project and you should include them if you need them explicitly (great example `manifold`).

**Comment by muhuk** [comment]
You are right. Thanks for the info.
