### ISSUE TITLE
Add preconditions to -mbind implementations

### ISSUE THREAD

**Issue by yurrriq** [funcool/cats#151]
Per #150, et al., `mlet` can be a little confusing wrt context. In an effort to fail faster (and not wait for #140), we should add preconditions to ensure the proper context in each `-mbind` implementation.

**Comment by yurrriq** [comment]
iirc protocol method implementations can't have `:pre`conditions, but a simple `if` that throws an error upon the encountering a contest mismatch should suffice.

**Comment by niwinz** [comment]
Working on it on #173

**Comment by niwinz** [comment]
What do you think about this:

```clojure
(require '[cats.context :as ctx] :reload)
(require '[cats.core :as m] :reload)
(require '[cats.monad.either :refer [left right]])
(require '[cats.monad.maybe :refer [just nothing]])

(m/mlet [a (just 1) b (right 2)] (m/return (+ a b)))
;; => #<Just 3>

(alter-var-root #'ctx/*strict* (constantly true))
;; => true

(m/mlet [a (just 1) b (right 2)] (m/return (+ a b)))
;; => IllegalArgumentException Context mismatch: you can't mix different context.  cats.context/throw-illegal-argument (context.cljc:33)
```

**Comment by niwinz** [comment]
It not yet finished (not in master) because I need some fixes before but is a generic approach instead of having assert on each -mbind impl. It just checks if the previously set context is equal to the current provided one and if they mismatches, then the exception is raised if strict mode is enabled.

**Comment by yurrriq** [comment]
I think the first example should always fail. The check and error message seem solid, though. What else does strict mode do?

**Comment by niwinz** [comment]
```clojure
(m/mlet [a (just 1) b (right 2)] (m/return (+ a b)))
;; AssertionError Assert failed: Monad type mismatch: #<Right 2> is not allowed to use with maybe context.
```

This seems like a much better error message and works as is, without strict mode.

**Comment by yurrriq** [comment]
Looks good to me.

**Comment by niwinz** [comment]
Nice, this is already in master ;)
