### ISSUE TITLE
CI builds do not fail on errors in cljs tests

### ISSUE THREAD

**Issue by sfnelson** [funcool/cats#158]
See https://travis-ci.org/funcool/cats/jobs/111481597

I've fixed this particular failure in my merge request for #157 but you probably want to address your ci scripts so that they won't pass on failing tests.

**Comment by yurrriq** [comment]
Fixed in #159. See 6bd186c6bde346108055d19e5ae75d6ae4c72109 [failures](https://travis-ci.org/funcool/cats/builds/112737214), for example.
