### ISSUE TITLE
Documentation: Mention promesa.monad

### ISSUE THREAD

**Issue by emnh** [funcool/cats#167]
I spent a while after upgrade to figure out that with new versions of promesa you have to require promesa.monad to use it with mlet.

The error I got was: No context is set and it can not be automatically resolved.

The examples should be updated.

**Comment by mattly** [comment]
It seems `promesa.monad` was removed from the most recent version of promesa, which makes using the two together somewhat problematic.

**Comment by niwinz** [comment]
Sorry for the inconvenience, the `promise.monad` was removed but it will be incorporated into cats in the same way as `promise.labs.manifold` so you will continue to use them together.

**Comment by niwinz** [comment]
Already fixed in #173
