### ISSUE TITLE
bind has different semantics than fmap

### ISSUE THREAD

**Issue by thurstonsand** [funcool/cats#186]
I may not understand the underlying reasoning, but `fmap` takes parameters `f mv` whereas `bind` takes `mv f`, so if you wanted to thread these it would be difficult. Is there a reason why the order is different?

**Comment by yurrriq** [comment]
As I understand it, cats is based (in part) on Haskell and its semantics. I've copied the relevant parts from `GHC.Base` here. N.B. `>>=` is pronounced *bind*.

```haskell
class  Functor f  where
    fmap        :: (a -> b) -> f a -> f b

class Applicative m => Monad m where
    -- | Sequentially compose two actions, passing any value produced
    -- by the first as an argument to the second.
    (>>=)       :: forall a b. m a -> (a -> m b) -> m b
```

The code above shows `fmap` takes a function from `a` to `b` and an `a` wrapped in a functorial context `f` then returns a `b` wrapped in the same functorial context `f`.

`>>=` or *bind* on the other hand, takes a monadic action `m a` and a function from `a` to a monadic action `m b` then returns an monadic action `m b`.

**Comment by thurstonsand** [comment]
gotcha. makes sense to be consistent with haskell... still don't know the reasoning behind the different ordering tho

**Comment by dialelo** [comment]
> still don't know the reasoning behind the different ordering tho

No reason other than the signatures of the Haskell methods. I agree that is a bit inconsistent.
