### ISSUE TITLE
Re-add state monad (or provide tips for why it's not needed in clojure)

### ISSUE THREAD

**Issue by caioaao** [funcool/cats#193]
I've seen some cases where a state monad was the only way to write proper functional code in clojure. If removing `state` monad is the final decision, it'd be cool if the docs would include an explanation on why it's not needed in clojure, with some examples :)

**Comment by niwinz** [comment]
If this is really usefull, I'm open to a PR for reverting that change ;)

**Comment by ericvm** [comment]
I'm working with a modified version of the state monad implementation of the previous cats version, I can open a PR for that with the changes I made, the previous implementation had some minor issues that I fixed

**Comment by ericvm** [comment]
https://github.com/funcool/cats/pull/210
