### ISSUE TITLE
Why is the implementation of rights not extracting the values from right?

### ISSUE THREAD

**Issue by ericvm** [funcool/cats#195]
In the implementation of `rights` from Haskell (https://hackage.haskell.org/package/base-4.9.1.0/docs/Data-Either.html), the right values are extracted from the either monad. Why is it not so in cats? The `rights` implementation from cats does not seem to be very useful if the values are not extracted.

**Comment by niwinz** [comment]
I'm not clearly understand that you are trying to say. The either values can be extracted with deref or using the `mlet` macro.

**Comment by ericvm** [comment]
If I have a list of eithers and I am selecting only the right values, it's because I'm interested in what they contain, there is no left value anymore, no need to keep the either abstraction. If I don't want to extract them, it's easy to write `(filter right? mylist)`. Also, this is compatible to what the `rights` function does in Haskell.

**Comment by yurrriq** [comment]
:+1: to making `rights` mirror the one in Haskell, i.e. take a list of `Either`s and return a list of the unwrapped `Right` values. Perhaps we could rename the current `rights` to `keep-rights` or similar.

**Comment by yurrriq** [comment]
Also the current docstring (in `master`) has a typo and should `s/left/right/` at least.
