### ISSUE TITLE
Please release fmap fix

### ISSUE THREAD

**Issue by szdavid92** [funcool/cats#209]
Hey all

using version 2.1.0, I noticed that in nested `fmap`s inner functors are coerced to the outermost's type or so:
```clj
user> (use 'cats.core)
nil
user> (use 'cats.builtin)
user> (fmap (fn [v] (fmap #(* 2 %) v)) #{[1 2 2]})
#{#{4 2}}
```

has this been fixed with #192 ?

I tried with the latest master (`6e6ff13`), and it seems that this works as expected now:

```clj
user> (fmap (fn [v] (fmap #(* 2 %) v)) #{[1 2 2]})
#{[2 4 4]}
```
However the latest release is still 2.1.0, which predates this fix.
When will be this released?

**Comment by ericvm** [comment]
I think this is just a matter of bumping cats to a different version, right? You could also clean your cache so that leiningen fetches the most current master version.

**Comment by szdavid92** [comment]
Oh I got mixed up, just realized that the version bump to 2.2.1 was only merged into a fork. 😅
I purged the cache and got a fresh release:
```
david@mac:~/Projects/ingraph/sre% lein repl
Retrieving funcool/cats/2.1.0/cats-2.1.0.pom from clojars
Retrieving funcool/cats/2.1.0/cats-2.1.0.jar from clojars
nREPL server started on port 51754 on host 127.0.0.1 - nrepl://127.0.0.1:51754
REPL-y 0.3.7, nREPL 0.2.12
Clojure 1.8.0
Java HotSpot(TM) 64-Bit Server VM 1.8.0_131-b11
    Docs: (doc function-name-here)
          (find-doc "part-of-name-here")
  Source: (source function-name-here)
 Javadoc: (javadoc java-object-or-class-here)
    Exit: Control+D or (exit) or (quit)
 Results: Stored in vars *1, *2, *3, an exception in *e

user=> (use 'cats.core)
WARNING: when already refers to: #'clojure.core/when in namespace: user, being replaced by: #'cats.core/when
WARNING: filter already refers to: #'clojure.core/filter in namespace: user, being replaced by: #'cats.core/filter
WARNING: sequence already refers to: #'clojure.core/sequence in namespace: user, being replaced by: #'cats.core/sequence
nil
user=> (use 'cats.builtin)
nil
user=> (fmap (fn [v] (fmap #(* 2 %) v)) #{[1 2 2]})
#{#{4 2}}
```
but it's still doesn't work.

What do you mean by 

>You could also clean your cache so that leiningen fetches the most current master version.

?
I thought that Leiningen fetches from clojars, or maven central, not GitHub.
And the latest version on Clojars is 2.1.0.

**Comment by ericvm** [comment]
In my case leiningen gets the most recent version, I don't know exactly why. My repositories are like this:

```
  :repositories  [["central"  {:url "http://repo1.maven.org/maven2/" :snapshots false}]
                         ["clojars"  {:url "https://clojars.org/repo/"}]
                         ["nu-maven" {:url "s3p://nu-maven/releases/"}]]
```

In any case, I think the latest changes are worth a version bump

**Comment by dustingetz** [comment]
+1, vendoring master fixed our problems with nested ctx too

**Comment by szdavid92** [comment]
Is this project dead? I only asked for releasing an already implemented fix 3 months ago, and it is still not done.

**Comment by yurrriq** [comment]
I don't use Clojure daily anymore, but I think I still have commit rights here still and could try to help fix things up, if needed.

**Comment by szdavid92** [comment]
@yurrriq The fix is already implemented and on master (https://github.com/funcool/cats/commit/4a5853e7338948cc8c398a6c6e92d5fe442c395d), but hasn't been released yet.

**Comment by yurrriq** [comment]
So we just need to release a new version then? I don't think I have permissions to push to clojars.

/cc @niwinz

**Comment by niwinz** [comment]
I go to release it right now!

**Comment by niwinz** [comment]
Done.
