### ISSUE TITLE
Reflections in the state monad

### ISSUE THREAD

**Issue by JAremko** [funcool/cats#216]
I'm getting reflection warnings in state.cljc:
```
Reflection warning, cats/monad/state.cljc:77:31 - reference to field fst can't be resolved.
Reflection warning, cats/monad/state.cljc:78:31 - reference to field snd can't be resolved.
```
Can they be type-annotated like in: https://github.com/funcool/cats/blob/e9060d5cabc94bd034e9257b4f5cf264822ba316/src/cats/data.cljc#L67

**Comment by JAremko** [comment]
I prolly also should ping @ericvm

**Comment by ericvm** [comment]
What are the steps to reproduce? I never had this kind of error.
I guess there is no harm in having a type hint.

**Comment by JAremko** [comment]
@ericvm  I think you just need to enable [`*warn-on-reflection*`](https://clojuredocs.org/clojure.core/*warn-on-reflection*)
