### ISSUE TITLE
2.3.0 not available on clojars

### ISSUE THREAD

**Issue by dharrigan** [funcool/cats#220]
Hi,

Seems the latest version is 2.2.0. Please can 2.3.0 be released to clojars.

Thank you

**Comment by dharrigan** [comment]
![screenshot](https://user-images.githubusercontent.com/427150/47644595-80de4e80-db66-11e8-99cf-518833c25696.png)

**Comment by ericvm** [comment]
I don't have permission to deploy to clojars :/

**Comment by dharrigan** [comment]
Hi,

Thank you for your reply. Apart from building locally, can you suggest another way to get the latest (2.3.0)?

-=david=-

**Comment by ericvm** [comment]
I guess you can use clojars to make an independent deploy yourself, it just won't be under https://clojars.org/funcool/cats

@niwinz Can you give permission for deploying on https://clojars.org/funcool/cats?

**Comment by ericvm** [comment]
I think it is better to consider the changes as "development" until a deploy is actually made

**Comment by niwinz** [comment]
hmm i think you should have a permision right now.
