### ISSUE TITLE
fmap or fapply with vararg?...and small question

### ISSUE THREAD

**Issue by cocodrino** [funcool/cats#29]
Hi...I'm not sure but I think than fmap or fapply must accept vararg ...

in haskell you can do
```haskell
ghci> pure (+) <*> Just 3 <*> Just 3
Just 6
```

in fluokitten  you can do

```clojure
(fmap * (just 5) (just 3))
;=> (just 15)
```

but I can't find how do it in cats avoiding nesting fmaps (maybe I'm missing something)

2) I've a code with channels where they can return a maybe type...which could be the best way of handle it, would be cool use mlet but I'm not sure if it's possible, just now I've 

```clojure
defn return-nothing []
   (let [c (a/chan 1)]
      (a/go (a/>! c nothing))
      c))

(defn return-just [v]
   (let [c (a/chan 1)]
      (a/go (a/>! c (just v)))
      c))


a/go(
 (let 
   [a (return-just 3)
   b  (fmap return-just (fmap (partial / 2) a))]
  (...)
)
```

**Comment by cocodrino** [comment]
ups..sorry must be [a (<! (return-just 3))]

basically I want to do something like this

```clojure
(defn send [addr msg]
  (let [ch (chan 1)]
    (eb/send addr msg #(put! ch %))
    ch))
 
(eb/on-message
  "console.laser"
  (fn [instructions]
    (go (let [coords (<! (send "rover.scope" (scope-msg instructions))) ;;this send can return nothing
              data (<! (send "rover.sensor" (sensor-msg coords))) ;;and in that case I need short circuit this
              power (calibrate-laser data) ;; and this.....
              status (<! (send "rover.laser" (laser-msg power)))]
          (eb/reply (parse-status status))))))

```

**Comment by dialelo** [comment]
Hi @cocodrino and thanks for using cats!

>(fmap * (just 5) (just 3))
>;=> (just 15)

> but I can't find how do it in cats avoiding nesting fmaps (maybe I'm missing something)

That behaviour of fmap doesn't align with what fmap is supposed to do. If i understand correctly, you want to use a function that works on non-monadic values (`*`) with monadic values. You can "promote" such function to work on monads with `cats.core.lift-m`, although it is limited to fixed arities at the moment.

For using `*` with monadic values you should do the following:

```clojure
(def monad-* (cats.core/lift-m 2 *))
;;                             ^ the desired arity

(monad-* (just 3) (just 5))           
;;=> Just 15  
```

Note that the generated function `monad-*` will work on any monad, not just maybe.

I hope this answered your first question. As for the second, @niwibe can help you better since he is currently working on a channel monad which you can combine with error monads, short-circuiting async computations.

**Comment by niwibe** [comment]
hi @cocodrino 

About using cats with core.async: the latest release does not incudes any facility for it.

Using cats mlet in go blocks with combination of put/take operations on channel not works out of the box becuse of nature of bind composition and go macro (go macro converts the code in a state machine that breaks the bind callbacks).

I'm currently developing an solution for provide a facility of use core.async channels and compose asynchronous computations with mlet macro (and obviously combine the channel with some error monad for short-circuiting async compitations). 

You can read the current documentation draft of that here: https://github.com/funcool/cats/blob/dbe22f5bebd1100a92c3f89ea66a10ad0a444428/doc/cats.adoc#55-channel

I'm sure that this facilities will be available in the next version ;)

**Comment by cocodrino** [comment]
thanks guys...@diadelo I agree with you, fmap in  fluokitten doesnt follow the category theory concepts, but I think than its approach is a bit more "lisp-ish" (+ 3 4 5 6) ... (fmap + (just 3) (just 4)) and it's nice for this kind of manipulation and it's a clever workaround to fixed arities..although lift-m is enough good for me right now   ...

@niwibe thanks, that is exactly what I need! :D ...I'll waiting the next release...

**Comment by yurrriq** [comment]
@cocodrino, you might be interested in [this discussion][1], which points to a couple [different][2] [implementation][3]s of auto-currying in Clojure.

`lift-m` is a good solution, but auto-currying might be even better (read: more Haskell-like).

[1]: https://groups.google.com/forum/#!topic/clojure/cE2FUrkPW8I
[2]: https://gist.github.com/sunilnandihalli/745654
[3]: https://gist.github.com/rlm/746185
