### ISSUE TITLE
More utilities for handling 'either'

### ISSUE THREAD

**Issue by jjl** [funcool/cats#37]
Hi,

I notice that a lot of functions I'm used to having around for handling Eithers in haskell are missing. In particularly, 'either', which provides for simple branching.

I've implemented it (as 'branch' to avoid having too many similarly named functions) and a few other things here: https://github.com/jjl/ednsl/blob/master/src/ednsl/util/either.clj

It's all MIT, so help yourself to anything you think is useful.

**Comment by dialelo** [comment]
Great suggestion, I will put them all in cats. Also I will take a look at the utility functions for Maybe et al and port those too. Thanks!

**Comment by niwibe** [comment]
+1 \o/

Thank you!

**Comment by yurrriq** [comment]
Related PR: #45
