### ISSUE TITLE
(m/fmap inc [1 2 3]) => IllegalArgumentException

### ISSUE THREAD

**Issue by somlor** [funcool/cats#42]
Forgive me if I'm misunderstanding something basic, I've only just begun reading the Cats Documentation.

Under the [5.1 Functor section](https://funcool.github.io/cats/latest/#_functor), there is an example of applying `fmap` to a vector that is raising an exception for me:
```
user=> (m/fmap inc (maybe/just 1))
#<Just@4b00df11: 2>
user=> (m/fmap inc [1 2 3])
IllegalArgumentException You are using return/pure/mzero function without context.  cats.core/get-current-context (core.clj:63)
```

Any help appreciated.

Thanks,
Sean

**Comment by niwibe** [comment]
He @somlor 

That is happens because you haven't imported the builtin namespace, that implements the monad and related protocols for clojure vector and other secuence types.

Let see:
```clojure
user=> (require '[cats.core :as m])
nil
user=> (m/fmap inc [1 2 3])
IllegalArgumentException You are using return/pure/mzero function without context.  cats.core/get-current-context (core.clj:63)

user=> (require 'cats.builtin)
nil
user=> (m/fmap inc [1 2 3])
[2 3 4]
```

**Comment by niwibe** [comment]
We do not want add monad implementation to clojure types until the user really wants that behavior.

**Comment by somlor** [comment]
@niwibe thanks for the explanation. Make perfect sense. I should have read the docs a bit further. :blush: Appreciate your help!
