### ISSUE TITLE
Applicative Do syntactic abstraction.

### ISSUE THREAD

**Issue by niwinz** [funcool/cats#46]
https://ghc.haskell.org/trac/ghc/wiki/ApplicativeDo

**Comment by dialelo** [comment]
I was playing around a bit today and I think we should implement this. As the wiki article mentions is a bit tricky to get right when having multiple operations that can happen in parallel. For the record, here is a library that implements a dependency graph: https://github.com/stuartsierra/dependency with topological sort. It may come in handy.
