### ISSUE TITLE
Foldable

### ISSUE THREAD

**Issue by dialelo** [funcool/cats#49]
https://hackage.haskell.org/package/base-4.7.0.2/docs/Data-Foldable.html#t:Foldable
https://wiki.haskell.org/Foldl_as_foldr
https://wiki.haskell.org/Foldr_Foldl_Foldl%27

**Comment by yurrriq** [comment]
I'd be happy to help, if you want, and would love to see/implement [`foldM`][1] too.

[1]: http://hackage.haskell.org/package/base-4.8.0.0/docs/Control-Monad.html#v:foldM

**Comment by niwinz** [comment]
Any help is welcome! \o/

**Comment by yurrriq** [comment]
Have you got a plan or task list? I wouldn't want anyone to duplicate their efforts.

**Comment by dialelo** [comment]
@yurrriq anything in the [issues list](https://github.com/funcool/cats/issues) that hasn't been assigned is ok, just comment if you want to work on it \o/ I've added a task for implementing `foldM` by the way.

**Comment by yurrriq** [comment]
:+1:

**Comment by niwinz** [comment]
merged
