### ISSUE TITLE
Clojars

### ISSUE THREAD

**Issue by yurrriq** [funcool/cats#54]
Is [`[funcool/cats "0.5.0"]`][1] the preferred dependency?

Or, can we expect a [`[cats "0.5.0"]`][2] soon?

[1]: https://clojars.org/funcool/cats/versions/0.5.0
[2]: https://clojars.org/cats

**Comment by yurrriq** [comment]
I'd love to upgrade my dependencies and ditch my project-local `branch-left`, `branch-right`, `invert`, etc.

**Comment by niwinz** [comment]
The `[funcool/cats "0.5.0"]` is a right way.  Almost all packages in the funcool organization uses the funcool groupid, and cats for historical motives does not do it until now.

**Comment by yurrriq** [comment]
Sounds great, thanks!
