### ISSUE TITLE
composing applicatives

### ISSUE THREAD

**Issue by mccraigmccraig** [funcool/cats#75]
i would like to compose applicatives for use with alet

i gather that this is achievable generically and doesn't require applicative transformers for each applicative type... though i can't find anything in cats atm 

does there need to be something in cats which reifies a context for such a composed applicative ?

**Comment by mccraigmccraig** [comment]
if you have an irc or slack or something and it would be more effective to ask questions there, point me to it... i had a look but couldn't find anything :)

**Comment by niwinz** [comment]
You can found us on clojurians.slack.com at #funcool channel. 

In any case I think @dialelo is the right person for respond your question.

**Comment by dialelo** [comment]
This may require us to implement an applicative instance that is aware of the nested applicative and use `with-context` for setting the context of the `alet` body, I'm going to investigate this further.

**Comment by yurrriq** [comment]
https://gitter.im/funcool/cats
