### ISSUE TITLE
[question]: Context and ContextClass protocols naming.

### ISSUE THREAD

**Issue by niwinz** [funcool/cats#85]
I would open a discussion for the `Context` and `ContextClass` protocol naming.

The last one (`ContextClass`) is introduced for identify the types that represent the context. And `Context` protocol exists for make the relation between the context type (now backed by `ContextClass`) and the concrete type, example: `Just` or `Nothing`.

As we know, at this moment the macro used for set up the context is `with-context`.

Having that in mind, that are the questions here:

- It make sense the `ContextClass` protocol name for identify a **context**? Maybe it should be named `Context`? seems to be more semantic.
- It make sense the `Context` class for identify the types that are related to some context? (in fact them are not context object). May be this protocol should be called `Contextual` or `ContextAware` or something similar?

**Comment by yurrriq** [comment]
Maybe `Context` and `ParentContext`, respectively.

**Comment by dialelo** [comment]
> It make sense the ContextClass protocol name for identify a context? Maybe it should be named Context? seems to be more semantic.

Agree.

> It make sense the Context class for identify the types that are related to some context? (in fact them are not context object). May be this protocol should be called Contextual or ContextAware or something similar?

+1 to `Contextual` but I'd love to hear the opinion of a native English speaker, @yurrriq what do you think?

**Comment by yurrriq** [comment]
I typed out a response quick response last night, I but I want to think on this a bit more. The proposed `Context` feels right; I'm just not sure about `Contextual` or the alternatives yet.

**Comment by yurrriq** [comment]
I speak Spanish by the way, which might come in handy if ever there's a language issue.

**Comment by niwinz** [comment]
As we know, in cats we have two main concepts:
- A context:  singleton immutable object that has associated implementations of the monad, applicative, etc... protocols; this objects satisfies the `ContextClass` protocol.
- A type: some clases that pertain to specific context; at this moment that relation is expressed with
`Context` protocol (that it means that all types, like Just, Nothing, Right,... satisfies `Context` protocol).

The current approach it is ok. But I think the protocol names used for represent the abstractions are wrong:
- `Context` protocol name is more likely a proper name for reprensent the context object instead of the type that belongs to some context.
- `ContextClass` is also wrong name, choiced because `Context` is already taken.

So the proposal to change is:

- Rename the protocol `Context` to `Contextual`; making the naming more semantical for types that are not contexts but belongs to one.
- Rename `ContextClass` to `Context`; because `Context` is a proper name for represent just the context.

My unique concern here is: `Contextual` is a good name?

@yurrriq, @dialelo : any objections?

**Comment by dialelo** [comment]
The current proposal is OK for me although I think there has to be something better than `Contextual`. I think that with this change we should document the extension of own types for participating in cats abstractions.

**Comment by yurrriq** [comment]
:+1: for documentation.

A common naming convention for protocols is using the suffix, `-{a,i}ble`. Since `Just` and `Nothing` are essentially constructors for instances of a `Maybe` `Context`<sup>1</sup>, what about `Constructible` or `Contextable`<sup>2</sup>?

Really, I think `Contextual` is fine. :)

<sup>1</sup> using the proposed redefinition
<sup>2</sup> not a proper word, but gets the point across

**Comment by mccraigmccraig** [comment]
Context / Contextual works for me - and the use of Contextual meets the dictionary definition - http://www.thefreedictionary.com/contextual

**Comment by yurrriq** [comment]
:shipit:
