### ISSUE TITLE
Travis test-clj.sh doesn't test all namespaces

### ISSUE THREAD

**Issue by Deraen** [funcool/cats#95]
https://github.com/funcool/cats/blob/master/.travis/test-clj.sh is missing `cats.labs.*` namespaces.

**Comment by Deraen** [comment]
Also, Leiningen 2.5.2 should fix the problem with `.cljc` files so I would suggest using it.

Travis still has 2.5.1 but running `lein upgrade` on dependecies step should fix that.

**Comment by niwinz** [comment]
You are right! I'll try to fix it with your suggestion.

Thanks!

**Comment by niwinz** [comment]
The `lein upgrade` approach does not works. So I have fixed it adding the missing namespaces.
