### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by alchayward** [funcool/cats#99]
Possible minor error in the documentation:

>The main difference between foldl and reduce is that *foldl* has a fixed arity so all parameters are mandatory and foldl is a generic abstraction that can work with other types apart from collections.

should be 

>The main difference between foldl and reduce is that *reduce* has a fixed arity so all parameters are mandatory and foldl is a generic abstraction that can work with other types apart from collections.

**Comment by niwinz** [comment]
Hmm, I think the documentation is correct. foldl has a fixed arity and reduce is variadic.
